# Data path. adjust them!
common:
    # image_file: "/home/allen/calib_data/cmu_pillar/cmu_pillar_thermal.png"
    image_file: "/home/allen/calib_data/ign_simulation/ldiar80.5_thermal810.5/320x240.png"
    # pcd_file: "/home/allen/calib_ws/data_demo/0lidar.pcd"
    # pcd_file: "/home/allen/calib_ws/data_demo/0edited.pcd"
    pcd_file: "/home/allen/calib_data/ign_simulation/ldiar80.5_thermal810.5/pcd/1.pcd"
    # pcd_file: "/home/allen/calib_data/cmu_pillar/cmu_pillar_lidar.pcd"
    # pcd_file: "/home/allen/calib_data/cmu_pillar/cmu_pillar_lidar_subsampled.pcd"
    result_file: "/home/allen/calib_data/ign_simulation/ldiar80.5_thermal810.5/640x320_results/640x320_4.txt"

# Camera Parameters. Adjust them!
camera:
    # camera_matrix: [276.87, 0.0,      160.0,
    #                             0.0,     207.65,  120.0,
    #                                             0.0,     0.0,      1.0     ]
    camera_matrix: [553.0, 0.0,      320.0,
                                0.0,     415.24,  240.0,
                                                0.0,     0.0,      1.0     ]
    # camera_matrix: [4700.987563588087141e+03, 0.0,      2.115184289108875873e+03,
    #             0.0,     4.718613209287033897e+03,  1.535121575201496853e+03,
    #             0.0,     0.0,      1.0     ]                
    dist_coeffs: [-0.0, 0.0, 0.0, 0.0, -0.0]
    # dist_coeffs: [-6.3682223e-02, 2.83812328e-01, 2.054823e-03, 3.36049e-03, -1.5568534e-01]

# Calibration Parameters.!
calib:
    calib_config_file: "/home/allen/thermal_range_calib_ws/src/thermal_range_calib/config/thermal_ign_config.yaml"
    # calib_config_file: "/home/allen/calib_ws/src/thermal_range_calib/config/ftm_left_config.yaml"
    use_rough_calib: false # set true if your initial_extrinsic is bad
